/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sergo.edf;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AppStarter {

    public static void main(String[] args) {
        SpringApplication.run(AppStarter.class, args);
    }

    public String getGreeting() {
        return "Hello world.";
    }
}
