package test.com.sergo.edf;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.sergo.edf.AppStarter;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppStarterTest {
    @Test public void testAppHasAGreeting() {
        AppStarter classUnderTest = new AppStarter();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
